#Postgres config
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: postgres
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/spring_reactive
    user: postgres
    password: password
management:
  endpoints:
    web:
      exposure:
        include: "*"
#server:
#  port: 8080
#  servlet:
#    context-path: "/${spring.application.api-version}"
#
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
    # Specify the path for Swagger UI

