# H2 Database Configuration
#spring.datasource.h2.username=sa
#spring.datasource.h2.password=password
#spring.h2.console.enabled=true
#spring.datasource.h2.url=jdbc:h2:mem:dcbapp
#spring.datasource.h2.driverClassName=org.h2.Driver

#Postgres config
spring.r2dbc.url